### ISSUE TITLE
Cool github project subtitle

### ISSUE THREAD

**Issue by yairchu** [Peaker/git-mediate#15]
"resolve trivial conflicts" doesn't sound cool.
Perhaps "the simple git conflict resolving tool" or something?

**Comment by Peaker** [comment]
How about "make conflicts fun again"?

**Comment by yairchu** [comment]
Heh, were conflicts ever fun? :)

**Comment by yairchu** [comment]
How about resolve conflicts peacefully?

**Comment by da-x** [comment]
One of the problems with the original naming 'trivial conflicts' was that it collided with the previous notion of what are trivial conflicts (modifications to the same files by different commits at different locations).

Also, regardless of what is 'trivial' this project does not resolve trivial conflicts by its own, but it relies on GSR and/or manual editing.

It is a CLI for conflict resolution *assistance*. 
CLICRA. 
קליק-רע.

**Comment by willsheppard** [comment]
The `--version` text has:

> Become a conflicts hero

I'd just use that on the README and repo summary.

**Comment by yairchu** [comment]
Great idea! I see that someone already updated the subtitle accordingly, so closing!
