### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by dglynch** [Peaker/git-mediate#17]
When I try to install `git-mediate` on a Windows machine, using either of the two installation methods, I get the following error message:

    Error: While constructing the build plan, the following exceptions were encountered:
    
    In the dependencies for unix-2.7.2.0:
        unbuildable must match <0, but the stack configuration has no specified version
    needed due to git-mediate-1.0.2 -> unix-2.7.2.0
    
    Plan construction failed.

Further investigation suggests this is caused by the line `unix >=2.7` in `git-mediate.cabal`, the naive removal of which results in compile-time errors due to missing interfaces such as `System.Posix.IO`.

According to [this page](https://hackage.haskell.org/package/unix), "The [unix] package is not supported under Windows."

Is the above analysis correct, and, if so, are there any plans to add Windows support for `git-mediate`?

**Comment by kthompson** [comment]
I was able to use under bash/WSL but `stack` wouldnt work, I had to use `cabal install`

**Comment by yairchu** [comment]
Works since https://github.com/Peaker/git-mediate/commit/0d7aa480f3cb4c48c9b14b4a64ccb350796b6349? Re-open if it doesn't..
