### ISSUE TITLE
failure on conflict resolution during rebase

### ISSUE THREAD

**Issue by danra** [Peaker/git-mediate#20]
The following conflict, gotten during a squash rebase, failed to resolve: (code shown is after manual edits done to solve the conflict):

```
<<<<<<< HEAD
    for (size_t x = 0; x < sizeof(addr.ip); ++x) {
||||||| parent of 8830bc707... ba
    for (size_t x = 0; x < sizeof(addr.ip); ++x) {
=======
    for (size_t x = 0; x < addr.ip.size(); ++x) {
>>>>>>> 8830bc707... ba

```
First and second snippets seem identical to me, so I guess this is an issue since this is a rebase-caused conflict?

**Comment by yairchu** [comment]
It might be an issue with white-space, probably "\n" vs "\r\n" at end of line

**Comment by danra** [comment]
@yairchu Probably not, looks like all line endings in the relevant source files are consistent (0x0a). Did you get a chance to successfully git-mediate a rebase-resulting conflict? Possibly it just doesn't work?

**Comment by yairchu** [comment]
I use it for rebase conflicts all the time

**Comment by yairchu** [comment]
Closing. This was probably due to whitespace, but (more fitting for a separate issue) to avoid confusion git-mediate should tell the user when the conflict is due to line-endings or whitespace.
