### ISSUE TITLE
Add to Homebrew

### ISSUE THREAD

**Issue by yairchu** [Peaker/git-mediate#36]
Many folks probably skip trying `git-mediate` simply because the install process isn't just `apt-get install git-mediate`

**Comment by pabs3** [comment]
I've [asked](https://bugs.debian.org/1041232) the Debian Haskell team to package git-mediate, hopefully they will be interested.

**Comment by clinty** [comment]
It may help to add explicit copyright statements and get it added to Stackage.

**Comment by yairchu** [comment]
> It may help to add explicit copyright statements and get it added to Stackage.

What is the benefit of adding a program to stockage?

I just did `stack install git-mediate --resolver=lts` and it works fine.

**Comment by clinty** [comment]
If the dependency tree stays as simple as it is now, it probably doesn't matter, but in theory it ensures that there's early warning if dependency versions won't be coinstallable when Debian upgrades to versions corresponding to the relevant Stackage LTS.

**Comment by pabs3** [comment]
git-mediate 1.0.8.1-1 has entered Debian unstable thanks to @clinty and the Debian archive admins.

**Comment by yairchu** [comment]
> It may help to add explicit copyright statements and get it added to Stackage.

It is now in [stackage nightly](https://www.stackage.org/nightly-2023-07-25). Thanks!

**Comment by AjaiKN** [comment]
I've submitted a PR to homebrew-core: https://github.com/Homebrew/homebrew-core/pull/150035.

**Comment by AjaiKN** [comment]
I forgot to mention here, the PR was accepted and it's now in Homebrew.

```bash
brew install git-mediate
```

**Comment by yairchu** [comment]
Fantastic, thanks!
