### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by wangp** [Peaker/git-mediate#37]
Would it be possible to make a new release, e.g. to include the file modes fix?

I also noticed that 1.0.8 and 1.0.8.1 don't have tags in the git repository.

**Comment by pabs3** [comment]
I am using the zdiff3 conflict style, the master branch supports it, but it would be nice to have a release that supports it, so I can use the Debian package (see #36) with zdiff3, since Debian only packages released versions.

**Comment by pabs3** [comment]
As well as the tags for 1.0.8 and 1.0.8.1 being missing, it seems they are missing from ChangeLog.md as well.

**Comment by yairchu** [comment]
> Would it be possible to make a new release, e.g. to include the file modes fix?
> 
> I also noticed that 1.0.8 and 1.0.8.1 don't have tags in the git repository.

Done and done

> As well as the tags for 1.0.8 and 1.0.8.1 being missing, it seems they are missing from ChangeLog.md as well.

Changelog fixed as well

Thanks!
